name: Bug Report 
description: Report a bug or request a feature for the Obsidian Plugin
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your contribution!


  - type: textarea
    id: issue-description
    attributes:
      label: What happened?
      description: Describe what happened and what you expected to happen.
      placeholder: Provide a detailed explanation of the issue.
    validations:
      required: true

  - type: checkboxes
    id: reproducible
    attributes:
      label: Is this issue reproducible?
      description: Can the issue be consistently reproduced?
      options:
        - label: I have checked if the issue is reproducible and can replicate it.

  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      description: What version of the plugin are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true


  - type: input
    id: platform
    attributes:
      label: What platform are you using?
      placeholder: "e.g., Windows, macOS, Linux"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please provide any relevant logs or errors. These will help in diagnosing the issue.
      placeholder: Paste log output here if applicable.
      render: shell
